name: moriko
description: "Library for weebs"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^12.1.1
  flutter_riverpod: ^2.4.6
  cached_network_image: ^3.3.0
  retrofit: ^4.0.3
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  riverpod_annotation: ^2.3.1
  dio: ^5.3.3
  google_fonts: ^6.1.0
  extended_image: ^8.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  device_preview: ^1.1.0
  pretty_dio_logger: ^1.3.1
  flutter_animate: ^4.2.0+1
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.2
  liquid_page: ^0.0.1
  url_launcher: ^6.2.1
  phosphor_flutter: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  analyzer: ^6.2.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.6
  freezed: ^2.4.5
  json_serializable:
  retrofit_generator: ^8.0.4
  go_router_builder: ^2.3.4
  icons_launcher: ^2.1.7

flutter_gen:
  output: lib/core/constants

  integrations:
    flutter_svg: false
    flare_flutter: false
    rive: false
    lottie: false

icons_launcher:
  image_path: "assets/meta/wolf.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/meta/logo.png